import { Book } from 'lucide-react';

const GLOSSARY_TERMS = [
  {
    term: "LLM SEO",
    definition: "The process of optimizing brand visibility and sentiment within the responses generated by Large Language Models like ChatGPT, Claude, and Gemini."
  },
  {
    term: "Visibility Score",
    definition: "A metric that quantifies how often and how prominently a brand is mentioned in the outputs of an AI model for a given set of queries."
  },
  {
    term: "Sentiment",
    definition: "The emotional tone or attitude conveyed by the LLM when mentioning a brand. Usually categorized as Positive, Neutral, or Negative."
  },
  {
    term: "Position",
    definition: "The order in which a brand is mentioned relative to its competitors in the LLM's response. Being mentioned first often carries more weight."
  },
  {
    term: "Brand Mention",
    definition: "Any instance where the specific name of a company, product, or service is generated in the text by an AI assistant."
  },
  {
    term: "Share of Voice",
    definition: "The percentage of mentions a brand receives compared to the total mentions of all tracked competitors for a specific topic or query."
  },
  {
    term: "Hallucination",
    definition: "When an LLM generates false, nonsensical, or unverified information about a brand that wasn't present in its training data."
  }
];

export default function GlossaryPage() {
  return (
    <div className="max-w-[1000px] mx-auto pb-12 animate-in fade-in duration-300">
      <div className="flex items-center space-x-3 mb-8">
        <div className="w-12 h-12 rounded-xl bg-accent/10 flex items-center justify-center">
          <Book className="w-6 h-6 text-accent" />
        </div>
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Glossary</h1>
          <p className="text-muted-foreground mt-1">Key terms and metrics used in LLM Search Engine Optimization.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {GLOSSARY_TERMS.map((item, idx) => (
          <div key={idx} className="bg-card border border-border rounded-xl p-5 hover:border-accent/50 transition-colors">
            <h3 className="text-lg font-semibold text-foreground mb-2">{item.term}</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">{item.definition}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
